name: Run FLStaticPatch

on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  patch:
    runs-on: windows-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v6
        with:
          path: freelancer-hd-edition
          ref: ${{ github.ref }}
          sparse-checkout: |
            DLLS
            EXE
            FLDOCS

      - name: Checkout patch tool repo
        uses: actions/checkout@v6
        with:
          repository: FLHDE/FLStaticPatch
          path: patching

      - name: Checkout original binaries repo
        uses: actions/checkout@v6
        with:
          repository: FLHDE/OriginalFLBinaries
          path: og-binaries

      - name: Replace binaries with originals
        run: |
          del og-binaries\README.md
          xcopy /s /y og-binaries freelancer-hd-edition

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Apply binary edits
        run: python patching/FLStaticPatch.py freelancer-hd-edition/FLDOCS/BinaryEdits.patch freelancer-hd-edition

      - name: Push changes to branch
        run: |
          cd freelancer-hd-edition
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'Apply binary edits'
          git push
