name: Update TSR DLLs

on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  update:
    runs-on: windows-latest
    if: ${{ github.actor != 'github-actions[bot]' && github.event_name != 'push' || github.event.pusher.name != 'github-actions[bot]' }}
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v6
        with:
          path: freelancer-hd-edition
          ref: ${{ github.ref }}
          token: ${{ secrets.PAT }}
          sparse-checkout: |
            EXE

      - name: Checkout TSR repo
        uses: actions/checkout@v6
        with:
          repository: FLHDE/freelancer-text-strings-revision
          path: tsr

      - name: Compile resource files
        run: |
          cd tsr
          compile-tsr-hde.bat
          cd ..
        shell: cmd

      - name: Replace all resource DLLs
        run: |
          del tsr\output\script.xml
          xcopy /s /y tsr\output freelancer-hd-edition

      - name: Push changes to branch
        run: |
          cd freelancer-hd-edition
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update TSR DLLs [skip ci]'
          git push

concurrency:
  group: push-${{ github.ref }}
